FROM php:8.1.3-fpm-alpine3.15

COPY wait-for-it.sh /usr/bin/wait-for-it

RUN chmod +x /usr/bin/wait-for-it

RUN apk --update --no-cache add git

RUN apk add yarn

RUN docker-php-ext-install pdo_mysql

RUN pecl channel-update pecl.php.net

RUN apk add nano

RUN apk add bash

# intl extension
RUN apk add icu-libs
RUN apk add --no-cache icu-dev
RUN docker-php-ext-install intl


# xdebug
RUN apk add autoconf
RUN apk add gcc
RUN apk add --no-cache $PHPIZE_DEPS \
    && pecl install xdebug-3.1.2 \
    && docker-php-ext-enable xdebug

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

CMD composer install ; wait-for-it recipesdb:3306 -- bin/console doctrine:migrations:migrate ;  php-fpm

EXPOSE 9000
EXPOSE 9003
